name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile program
        run: g++ -std=c++17 -o program lab3_ci.cpp
      - name: Run program
        run: ./program

  clang-format:
    runs-on: ubuntu-latest
    container: ghcr.io/cpp-linter/clang-tools:18
    steps:
    - uses: actions/checkout@v4
    - run: clang-format --dry-run lab3_ci.cpp
      continue-on-error: true

  clang-tidy:
    runs-on: ubuntu-latest
    container: ghcr.io/cpp-linter/clang-tools:18
    steps:
    - uses: actions/checkout@v4
    - run: clang-tidy lab3_ci.cpp -- -std=c++17
      continue-on-error: true